[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.1.4"

[[constraint]]
  name = "github.com/go-restit/lzjson"
  branch = "master"

[[constraint]]
  name = "gopkg.in/vmihailenco/msgpack.v2"
  version = "^v2.9.1"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "^v0.3.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "^v1.4.0"

[[constraint]]
  name = "github.com/bradfitz/gomemcache"
  branch = "master"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "^v1.1.0"

[[constraint]]
  name = "gopkg.in/redis.v3"
  version = "^v3.6.4"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "^v2.1.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/go-cmp"
  branch = "master"
