version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bukalapak/ottoman
    docker:
      - image: circleci/golang:1.8
      - image: redis:3.2-alpine
      - image: memcached:1.4-alpine
    steps:
      - checkout
      - run: go version
      - cache-restore:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure -v
      - cache-save:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Configure the build
          command: |
            sudo apt-get -qq update
            sudo apt-get install -y ruby
            sudo gem install redis
            sed -i '/gem install redis/d' scripts/redis-cluster.sh
      - cache-restore:
          key: redis-cluster-{{ checksum "scripts/redis-cluster.sh" }}
      - run: make redis-cluster-start
      - cache-save:
          key: redis-cluster-{{ checksum "scripts/redis-cluster.sh" }}
          paths:
            - redis-cluster
      - run: go get -u gopkg.in/alecthomas/gometalinter.v1
      - run: make check && make coverage
      - run: make redis-cluster-stop
      - run: bash <(curl -s https://codecov.io/bash) -t 13ff258b-f057-4ddf-af7d-d5aa26798fdc

