version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bukalapak/ottoman
    docker:
      - image: circleci/golang:1.10-stretch
      - image: redis:3.2-alpine
      - image: memcached:1.4-alpine
      - image: grokzen/redis-cluster:3.2.10
    steps:
      - checkout
      - run: go version
      - cache-restore:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - run: make dep
      - run: make dep-ensure
      - cache-save:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run: make check && make coverage
      - run: bash <(curl -s https://codecov.io/bash)

